import { HealthMonitorManager } from './health-monitor-manager';
export { AlertData, BloodPressureValue, PnsZone, Rect, SnsZone, StressLevel, VitalSigns, VitalSignsResults, VitalSignType, WellnessLevel, ConfidenceLevel } from './common/types';
export { DeviceOrientation } from './device/types';
export { HealthMonitorManagerOptions } from './health-monitor.types';
export { HealthMonitorCodes } from './health-monitor-codes';
export { FaceSessionOptions, HealthMonitorSession, SessionState, SubjectDemographic, Gender, SUBJECT_DEMOGRAHIC_THRESHOLD, } from './session/session.types';
export { LicenseOptions, EnabledVitalSigns, OfflineMeasurements, } from './license/license.types';
export { getOS, isMobile, isTablet, isIos } from './device/device';
declare const _default: HealthMonitorManager;
export default _default;
